### ISSUE TITLE
Fail on RaspberryPi 4 (Unable to open DISPLAY)

### ISSUE THREAD

**Issue by manoleitor977** [bell-sw/Liberica#43]
Hello,
I want to use JavaFX on my Raspberry Pi4, but I've encountered one problem.
The version I'm using is JDK 16 For Linux ARM 32 bit (Full JDK). Installed via wget and sudo apt install.
I'm using a 5 inch touch screen (http://www.lcdwiki.com/5inch_HDMI_Display-B).
I have installed Raspberry PI OS (full), sudo apt update and upgrade, I commented the line in /boot/config.txt (#dtoverlay=vc4-fkms-v3d) and using one Hello_world.jar with `sudo java -jar Hello_world.jar`, I always get this error:
`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:144)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:288)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
        ... 5 more
`

I've also tried changing 
`cd /opt/vc/lib `
`sudo ln -s libbrcmEGL.so libEGL.so `
`sudo ln -s libbrcmGLESv2.so libGLESv2.so  `
and trying with `-Djavafx.platform=gtk`

but this doesn't seem to work. Has anyone have this problem?

**Comment by AlexanderScherbatiy** [comment]
Which way do you use to run JavaFX on Raspberry Pi?

I tried jdk16 arm32-vfp-hflt full version from  [bell-sw](https://bell-sw.com/pages/downloads/#/java-16-current) on Raspberry Pi 4 with Raspbian 10 (buster) with  Raspberry Pi 7" Touch Screen Display.

I can run a JavaFX app directly attaching a mouse and a keyboard to Raspberry Pi and writing the command in a shell window which I opened in Raspbian desktop or connecting to Rasperry Pi via VNC.
```
java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36)
OpenJDK Server VM (build 16+36, mixed mode)

java HelloWorld
```
This works for me with Legacy GL driver. I used `sudo raspi-config` and the /boot/config.txt is
```
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
```

and with GL (Fake KMS)
```
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
dtoverlay=vc4-fkms-v3d
```

If I connect to Raspberry Pi4 using ssh and run JavaFX I also see ` Unable to open DISPLAY` exception. Running UI using ssh requires using '-X' option:
```
ssh -X pi@host
java HelloWorld
```

In this case I see the HelloWorld JavaFX app but it is shown not in Raspberry Pi but on my  Linux system which I use to connect to Raspberry Pi.
```

**Comment by voitylov** [comment]
Closing as it seems to be a configuration issue.

**Comment by maebli** [comment]
We have the same issue in a project as stated by OP. What configuration resolves this issue?
